### ISSUE TITLE
jspm install fails behind proxy

### ISSUE THREAD

**Issue by yeban** [jspm/jspm#10]
```
$ jspm install github:jquery

Getting version list for github:jquery
err  Error looking up version for jquery
     ssh: connect to host github.com port 22: Connection refused
     fatal: Could not read from remote repository.

     Please make sure you have the correct access rights
     and the repository exists.

     Config file updated.
     package.json updated.
warn Install finished, with errors.
```

**Comment by faceleg** [comment]
Has this been resolved?

`jspm install` is not working for me, I have `$http_proxy` and `$https_proxy` values in the env (and their uppercase kin).

**Comment by guybedford** [comment]
@faceleg thanks for posting - where abouts is the install falling over? It would help to know, as I don't have an easy testing environment for the proxy work my side.

**Comment by tauren** [comment]
I've had no proxy problems with jspm since the `request ` module was fixed.
However I am also using a recent version of `npm` that also depends on the
fixed `request` module. More details about your environment would help.

**Comment by faceleg** [comment]
@guybedford the furthest I got with debugging this was: https://github.com/jspm/jspm-cli/blob/master/lib/package.js#L456. Where is `getPackageConfig` declared?

**Comment by faceleg** [comment]
@tauren `npm:font-awesome` installs successfully, github repos are failing. My proxy disallows SSH, if that is relevant.

**Comment by guybedford** [comment]
@faceleg that could well be it. Does it fail on the lookup or download stage? jspm github uses `git` in the background to do the lookups in https://github.com/jspm/github/blob/master/github.js#L285. Please do let me know if you manage to debug that further.

**Comment by guybedford** [comment]
@faceleg perhaps log the exec command as well and see if you can run that from the command line ok.

**Comment by faceleg** [comment]
@guybedford fails on the download stage - the exec command works in jspm and on my CLI

**Comment by guybedford** [comment]
@faceleg thanks for letting me know.

The next three things to check are:

* getPackageConfig - https://github.com/jspm/github/blob/master/github.js#L338
* download, checkReleases - https://github.com/jspm/github/blob/master/github.js#L524
* download, from git archive - https://github.com/jspm/github/blob/master/github.js#L493

**Comment by faceleg** [comment]
Updating `jspm-github`'s `request` to 2.51 solved this for me. Want a PR?

**Comment by faceleg** [comment]
Waiiiitaminute, I see the GH module hasa 2.51 listed at https://github.com/jspm/github/blob/master/package.json#L22 but wasn't in mine, investigating.

**Comment by faceleg** [comment]
The `v0.9.11` jspm-github that gets installed *doesn't* have the 2.51 request version listed in it's package json.

**Comment by guybedford** [comment]
@faceleg nice!! The request update is in the master branch, not yet released - release should be out tomorrow with some luck.

**Comment by faceleg** [comment]
Cool. I guess re-close this then

**Comment by sylvainpolletvillard** [comment]
I have the same problem with my company proxy on Windows 7 :

    jspm install github:jquery

    warn Error on locate for github:jquery, retrying (1).
     Error: tunneling socket could not be established, cause=10000:error:140770FC:SSL    routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:795:

         at ClientRequest.onError    (C:\Utilisateurs\a526177\AppData\Roaming\npm\node_modules\jspm\node_modules\jspm-github\node_modules\request\node_modules\tunnel-agent\index.js:168:17)
         at ClientRequest.g (events.js:180:16)
         at ClientRequest.emit (events.js:95:17)
         at CleartextStream.socketErrorListener (http.js:1551:9)
         at CleartextStream.emit (events.js:95:17)
         at SecurePair.<anonymous> (tls.js:1410:15)
         at SecurePair.emit (events.js:95:17)
         at SecurePair.error (tls.js:1017:27)
         at CleartextStream.read [as _read] (tls.js:462:17)
         at CleartextStream.Readable.read (_stream_readable.js:340:10)

Same error for a NPM dependency. However, I don't have this issue with the "npm install" command.

Here is what I try :
- HTTP_PROXY and HTTPS_PROXY environment variables set to http://mycompanyproxy:port
- in my global npm config, C:\Utilisateurs\a526177\.npmrc
https-proxy = "http://mycompanyproxy:port"
proxy = "http://mycompanyproxy:port"
- in my global git config, 
url.https://.insteadof=git://
http.proxy=http://mycompanyproxy:port
https.proxy=http://mycompanyproxy:port

Can you explain what is this error message and how can I solve this ? Thanks in advance

**Comment by guybedford** [comment]
One thing to note is that `github:jquery` is not a valid install - try `github:components/jquery` rather.

Also ensure you have locally configured `git` to use the proxy as jspm calls out to the git command.

Apart from that I must admit I don't have much of a clue when it comes to proxies. Perhaps someone else here with more experience can help.

**Comment by sylvainpolletvillard** [comment]
I got the same error with `github:components/jquery` and ``npm:font-awesome``. But it worked if if I use directly ``git clone`` or ``npm install`` commands. I'll check my local git configuration when I get back to work.

**Comment by capaj** [comment]
@guybedford it is the same on the W7 machines behind proxy at a company I recently joined. I have git configured with 
```
git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080
git config --global https.proxy https://proxyuser:proxypwd@proxy.server.com:8080
```
and my installs fail with:
```
C:\test>jspm i jquery
Package.json file does not exist, create it? [yes]:
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]
:
Enter server baseURL (public folder path) [./]:
Enter jspm packages folder [.\jspm_packages]:
Enter config file path [.\config.js]:
Configuration file config.js doesn't exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Which ES6 transpiler would you like to use, Traceur or Babel? [babel]:
     Updating registry cache...

warn Error on locate for github:components/jquery, retrying (1).
     Error: getaddrinfo ENOTFOUND github.com github.com:443
         at errnoException (dns.js:25:10)
         at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

warn Error on locate for github:components/jquery, retrying (2).
     Error: getaddrinfo ENOTFOUND github.com github.com:443
         at errnoException (dns.js:25:10)
         at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
^CChcete ukončit dávkovou úlohu (A/N)?
^C
C:\test>jspm i lodash
Package.json file does not exist, create it? [yes]:
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]
:
Enter server baseURL (public folder path) [./]:
Enter jspm packages folder [.\jspm_packages]:
Enter config file path [.\config.js]:
Configuration file config.js doesn't exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Which ES6 transpiler would you like to use, Traceur or Babel? [babel]:
     Updating registry cache...
     Looking up npm:lodash

warn Error on lookup for npm:lodash, retrying (1).
     Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
         at errnoException (dns.js:25:10)
         at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

warn Error on lookup for npm:lodash, retrying (2).
     Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
         at errnoException (dns.js:25:10)
         at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

warn Error on lookup for npm:lodash, retrying (3).
     Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
         at errnoException (dns.js:25:10)
         at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

warn Error on lookup for npm:lodash
     Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
         at errnoException (dns.js:25:10)
         at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

err  Error looking up npm:lodash.

warn Installation changes not saved.
```

**Comment by guybedford** [comment]
@capaj we don't support the global config - proxy is handled entirely via environment variables, as described in https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables.

**Comment by IcodeNet** [comment]
I hope my comment will help to understand the root of the problem.
The error I was getting when running from a command prompt: 'jspm install'
was 
.....
Error on locate for github:
Error: connect ECONNREFUSED
......

In my case the issue was repeatable and it had to do with running the 'jspm install' under an administrator console. 

I have managed to resolve this in two ways:
* 1.) fire up normal cmd and then run again 'jspm install'
* 2.) in the administrator cmd, run 
               SET HTTP_PROXY=<Corporate_Proxy>
               SET HTTPS_PROXY=<Corporate_Proxy>
                install jspm


Following any of the above steps it resolved my issue.

**Comment by MaluTom** [comment]
I'm having a similar issue whereby my jspm installs are failing behind proxy - 

```
Error: tunneling socket could not be established, cause=write EPROTO 101057
ssl\s23_clnt.c:782:

         at ClientRequest.onError (c:\[path]\node_modules\jsp
js:174:17)
         at ClientRequest.g (events.js:199:16)
         at ClientRequest.emit (events.js:107:17)
         at TLSSocket.socketErrorListener (_http_client.js:271:9)
         at TLSSocket.emit (events.js:129:20)
         at onwriteError (_stream_writable.js:317:10)
         at onwrite (_stream_writable.js:335:5)
         at WritableState.onwrite (_stream_writable.js:105:5)
         at fireErrorCallbacks (net.js:456:13)
         at TLSSocket.Socket._destroy (net.js:495:3)

```

I've tried setting the http/s proxy env variables as described in the post but I still can't get around it. My jspm-github component is on version - 0.11.6

Any advice?

**Comment by JabX** [comment]
Hi,
I have the same exact error messages that @capaj is getting on Windows behind my company's proxy.
npm install works, git clone works, but somehow jspm install fails.
I of course tried to set the env variables like everyone else.

Any ideas ?

**Comment by guybedford** [comment]
I would love for someone to suggest what needs to be done here myself. I have no test cases for proxys, so find this very difficult to work on.

**Comment by uoloman** [comment]
Same issue. Doesn't work behind corporate proxy on windows 7. This is blocker in using jspm.

>node -v
v0.12.7

>npm -v
2.14.1

Trying to run http://aurelia.io/get-started.html example.

Neither "jspm install -y" or "jspm registry config github" works. 
Files are getting downloaded properly with npm install command. Only failing with jspm.


proxy and https-proxy are correctly set in npm config (hence npm works proplery but not jspm).

Also, tried setting http_proxy and https_proxy in windows console as env variable but no luck.

**Comment by uoloman** [comment]
In case someone wants to know this is not being run with admin access.

error 
>jspm install -y

warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.
     Looking up npm:babel-core
     Looking up npm:babel-runtime
     Looking up npm:core-js

warn Using local override for npm:core-js@0.9.18
     Looking up npm:font-awesome
     Creating registry cache...

warn Error on locate for github:aurelia/animator-css, retrying (1).
     Error: getaddrinfo ENOTFOUND github.com
         at errnoException (dns.js:44:10)
         at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)

warn Error on locate for github:aurelia/binding, retrying (1).
     Error: getaddrinfo ENOTFOUND github.com
         at errnoException (dns.js:44:10)
         at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)

**Comment by uoloman** [comment]
It worked only after adding HTTP_PROXY and HTTPS_PROXY as user environment variables.  Earlier I was just setting those two variables on command prompt using following command which didn't work.
>set HTTP_PROXY="<proxy>" command

However after this I got following error
```
     Error: certificate not trusted
         at Error (native)
```

To resolve this error - set "strictSSL": false, in C:\Users\<username>\AppData\Local\.jspm\config file
(mode detail - https://github.com/jspm/jspm-cli/issues/725)

After which following command worked fine.
>jspm registry config github

However, now I'm getting below error. Any idea how to fix it ? Thnx.
```
warn Error on getOverride for jspm:npm
     Error: Command failed: C:\Windows\system32\cmd.exe /s /c "git fetch --all && git reset --hard origin/master"
     fatal: unable to access 'https://github.com/jspm/registry.git/': SSL certificate problem: unable to get local issuer certificate
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:751:12)
         at ChildProcess.emit (events.js:110:17)
         at maybeClose (child_process.js:1015:16)
         at Socket.<anonymous> (child_process.js:1183:11)
         at Socket.emit (events.js:107:17)
         at Pipe.close (net.js:485:12)

warn Error on getOverride for jspm:npm
     Error: Command failed: C:\Windows\system32\cmd.exe /s /c "git fetch --all && git reset --hard origin/master"
     fatal: unable to access 'https://github.com/jspm/registry.git/': SSL certificate problem: unable to get local issuer certificate
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:751:12)
         at ChildProcess.emit (events.js:110:17)
         at maybeClose (child_process.js:1015:16)
         at Socket.<anonymous> (child_process.js:1183:11)
         at Socket.emit (events.js:107:17)
         at Pipe.close (net.js:485:12)

warn Error on getOverride for jspm:npm
     Error: Command failed: C:\Windows\system32\cmd.exe /s /c "git fetch --all && git reset --hard origin/master"
     fatal: unable to access 'https://github.com/jspm/registry.git/': SSL certificate problem: unable to get local issuer certificate
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:751:12)
         at ChildProcess.emit (events.js:110:17)
         at maybeClose (child_process.js:1015:16)
         at Socket.<anonymous> (child_process.js:1183:11)
         at Socket.emit (events.js:107:17)
         at Pipe.close (net.js:485:12)
```

**Comment by smialy** [comment]
I have some problem with proxy too. After run: 
```bash
jspm install 
```
I have:  Error: fatal: unable to access 'systemjs/plugin-text.git/': Could not resolve host: github.com
How I fixed it? 
I've removed next three line: https://github.com/jspm/github/blob/0.13.7/github.js#L113 - :(
