### ISSUE TITLE
Injecting a deno map, breaks

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm#118]
Replication:

```
jspm install @babel/core --env deno
jspm inject @babel/core test.html --env browser,production
```

Creates a `process.ts` mapping in the import map which doesn't execute.

**Comment by Aslemammad** [comment]
I do not know what is the reason and the cause for this. Maybe it's an upstream issue?

**Comment by guybedford** [comment]
Yes it could be a generator bug, perhaps try create a failing test PR for the generator at least?

**Comment by Aslemammad** [comment]
sure, meanwhile, it'd be good if you'd review the PR. Thank you so much.

**Comment by Aslemammad** [comment]
https://github.com/jspm/generator/pull/193

**Comment by Aslemammad** [comment]
Let's close this as an upstream issue.
