### ISSUE TITLE
link install test

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm#129]
Self-hosting is always a great test:

```
jspm install jspm=./ --env=deno
```

_plus_ a Deno or Node.js execution of the above to ensure it can run itself, something like:

```
deno --unstable -A --importmap importmap.json jspm.js install jspm=./ --env=deno
```

where `importmap.json` is the full import map for Deno that runs JSPM itself.

**Comment by guybedford** [comment]
I think this should actually be using the `trace-install` feature:

```
jspm trace-install ./jspm.js --env=deno
deno --unstable -A --importmap importmap.json ./jspm.js trace-install ./jspm.js --env=deno
```

**Comment by guybedford** [comment]
(whether it works is another question though! It may well not, in which case a simpler test would suffice)

**Comment by Aslemammad** [comment]
![image](https://user-images.githubusercontent.com/37929992/212179624-2b4106be-6504-493c-b58b-e805fbafd654.png)

It says module not found.

**Comment by guybedford** [comment]
Here's a simpler test:

```
import chalk from 'chalk';

console.log(chalk.bold('Chalk works'))
```

With:

```
 node jspm.js link ./test.js --env=deno,node
```

and:

```
deno --unstable run --importmap importmap.json -A test.js
```
