### ISSUE TITLE
Error message handling

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm#137]
We should have "nice" error output when possible. For example when:

* Generator errors return `JspmError` for all errors that don't need an error stack (non-internal errors). We only need to show the message for these.
* Similarly errors with nice messages thrown from within the CLI code itself don't need error stacks - `throw new Error('import map not found')` doesn't need to log a stack. So we distinguish between internal errors that do need a stack and _nice errors_ which can be stackless. There's a few techniques for this, I quite like the separate error class for non-stack errors `throw new JspmError(...)` where `class JspmError extends Error { constructor () { super() } }` and that's it.

**Comment by Aslemammad** [comment]
I'd handle this after #140 since it has some changes related. let me focus on other issues.
