### ISSUE TITLE
baseURL handling

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm#138]
Generator has `baseURL`, `mapURL` and `rootURL`.

We should be passing `baseURL` and `mapURL` explicitly:

* `baseURL` - `pathToFileURL(process.cwd())`
* `mapURL` - `pathToFileURL(resolve(mapPath))`

**Comment by Aslemammad** [comment]
I added them, but I'd like to see a basic test/example for it so I add it to the tests.
