### ISSUE TITLE
jspm inject usability

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm#147]
when providing the wrong first argument, one ends up with weird package name files being written.

Instead let's make the html file argument a mandatory flag:

```
jspm inject --html test.html react-dom
```

If the flag isn't provided we should get an error:

```
jspm inject react-dom

ERR: Must provide an --html file to inject into
```

**Comment by guybedford** [comment]
We could use `-h` as a short flag for `--html`.

**Comment by Aslemammad** [comment]
I think -h would be confusing with --help! So let's skip it IMO.
