### ISSUE TITLE
Installing with `-o` as target should pick up the `env` if there are any existing

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [jspm/jspm#170]
Adding issues, as i am testing. When we run `jspm install` with `-o` flag. If the file is present, we need to respect the `env`. I the recording you can see that the env is being changed to `browser` back from `node`

https://user-images.githubusercontent.com/11075561/222828643-d3dea207-9c13-40b1-a4cb-5051acc56fc0.mov

**Comment by JayaKrishnaNamburu** [comment]
And it would be great, if we can detect these `-o` files somehow. And no need to pass all the flags every time would be great. Like first if we run 

```sh
jspm install react-dom@17 -o node.importmap -e node,production,module
```

Next time, if we run

```sh
jspm install react@17 -o node.importmap
```

it should pick up the `-e` attributes.

**Comment by JayaKrishnaNamburu** [comment]
Ah, i found it. The thing is we are overwriting the file. So, it's resetting the things every time. Should be straight forward if we check for file existence 👍

**Comment by guybedford** [comment]
The same workflow should already work with the `-m` flag for the input map.

That is - `jspm install -m node.importmap` should behave as you are expecting here.

`jspm install -o node.importmap` does not read the `node.importmap` file at all.

**Comment by JayaKrishnaNamburu** [comment]
Interesting, works as expected with `m` flag. But, i would like to see this as default behaviour. Maybe i am just used to how `npm install` works by default it updates anything existing.

**Comment by guybedford** [comment]
Yeah, basically, the `-o` flag is only for injection into HTML now and for pruning wanted dependencies eg `jspm link ./local.js -o localapp.html`. I think this is a confusion due to the way the API has changed over time and as long as one is properly introduced to the patterns we can avoid this confusion.
