### ISSUE TITLE
Provider switching not supporting custom mappings

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm#189]
If I have a custom mapping:

_importmap.json_
```
{
  "imports": {
    "app": "./src/app.js",
    "lit": "https://ga.jspm.io/npm:lit@2.7.0/index.js"
  },
  "scopes": {
    "https://ga.jspm.io/": {
      "@lit/reactive-element": "https://ga.jspm.io/npm:@lit/reactive-element@1.6.1/reactive-element.js",
      "lit-element/lit-element.js": "https://ga.jspm.io/npm:lit-element@3.3.0/lit-element.js",
      "lit-html": "https://ga.jspm.io/npm:lit-html@2.7.0/lit-html.js",
      "lit-html/is-server.js": "https://ga.jspm.io/npm:lit-html@2.7.0/is-server.js"
    }
  }
}
```

and I install to a new provider:

```
jspm install --provider nodemodules
```

I get this error:

```
Error: Unable to resolve package npm:app in range "*" from parent file:///C:/Users/Guy/Projects/test/
```

We should be able to detect the custom mapping from the decomposition process and know not to try to switch providers on an entry that doesn't come from a provider.

**Comment by guybedford** [comment]
In addition, the `nodemodules` should probably have a slightly better error for these resolution errors.

Rather than just saying `cant resolve`, we should say:

```
node_modules/app does not exist, try installing it with npm first with "npm install app"
```

**Comment by Bubblyworld** [comment]
Ah, I think what's actually going on here is that since you didn't specify a package to install, it's reinstalling all top-level imports (including "app"), and "app" is being interpreted as the package "npm:app" by the generator.
