### ISSUE TITLE
No browser working weirdly?

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm#192]
When using comma separation, it seems to end up with a malformed condition name:

```
jspm install deno:crypto -m deno.json --env=deno,no-browser
```

Gives:

```
"env": [
    "deno",
    "deno no-browser",
    "development",
    "module"
  ],
```

Once in this state, it can't easily be corrected without manual intervention.

`-e=deno -e=no-browser` does work though.

_(corrected)_

**Comment by Bubblyworld** [comment]
<img width="1012" alt="Screenshot 2023-04-03 at 12 26 42" src="https://user-images.githubusercontent.com/6214591/229483915-8451e447-2349-44d8-90b7-c15ab57d6cae.png">

Hmm, can't reproduce this one locally - could you run with `JSPM_CLI_LOG=1` and paste the logfile maybe?

**Comment by guybedford** [comment]
Will reopen if I can reproduce.
