### ISSUE TITLE
Add support for creating module preloads for only the static dependencies 

### ISSUE THREAD

**Issue by dasa** [jspm/jspm#2518]
It currently seems to also create `modulepreload`'s for the dynamic imports. I'd like these to only be loaded as needed.

**Comment by guybedford** [comment]
We could definitely add a `--preload-static`. Perhaps we could even make it the default and have `--preload=dynamic` for doing both static and dynamic preloading, where `--preload=static` is the default.

**Comment by dasa** [comment]
making it the default sounds good 😄
