### ISSUE TITLE
Relative path imports in react-dom (dev), react-intl, semantic-ui-react

### ISSUE THREAD

**Issue by MilanKovacic** [jspm/jspm#2540]
Hi, I was under the impression that jspm install generates "self-contained" imports.

In the case of aforementioned libraries, this is not the case, as they contain relative path imports, for example, react-dom development (https://ga.jspm.io/npm:react-dom@18.2.0/dev.index.js) contains import{e as t}from"./_/0d6efdcf.js".

Here are 3 packages that exhibit this behavior:

https://ga.jspm.io/npm:react-dom@18.2.0/dev.index.js
https://ga.jspm.io/npm:react-intl@6.4.4/lib/index.js
https://ga.jspm.io/npm:semantic-ui-react@2.1.4/dist/es/index.js

Is this the intended behavior, or? This presents problems when import map packages are downloaded locally (and import map rewritten) for use in restricted environments.

**Comment by guybedford** [comment]
JSPM generates import maps only for bare specifiers and host imports which require mapping.

Relative specifiers will be left in-tact and this is important to reducing the size overhead of the import map as well.

If you are looking for self-contained downloads of packages, you can read the package.json for a package on the JSPM CDN and use the `files` key to determine which files to download for the package.

**Comment by MilanKovacic** [comment]
Understood. The soluton with locating, and downloading files from package.json will work.
