### ISSUE TITLE
ERROR Module not found ABC

### ISSUE THREAD

**Issue by schlichtanders** [jspm/jspm#2569]
Hi there, I am trying to run `jspm install "@mui/icons-material" --provider nodemodules`, but it fails with the following note

```
Error: Module not found: file:///home/myhome/MyPackage/node_modules/@mui/icons-material/esm/Abc imported from file:///home/myhome/MyPackage/node_modules/@mui/icons-material/esm/index.js
```

I guess this is due to that jspm does not automatically resolve `import "./Abc"` to `import "./Abc.jl"`

**Comment by guybedford** [comment]
Yes, the nodemodules provider follows the Node.js resolution rules, which do not include extension searching. This is a limitation of using the nodemodules provider to resolve ESM that was designed to be loaded with bundlers and not through Node.js directly.

Instead use a provider that can handle fixing these resolution changes like jspm.io.
